### ISSUE TITLE
Life Cycle Ending Documentation

### ISSUE THREAD

**Issue by Template0Dev** [Locked15/UksivtSchedule_ClientSchedule#23]
As I think, it will be good, if documentation for this project will be complete.
And not like for Rebooted Admin Tools.
![image](https://github.com/Locked15/UksivtSchedule_ClientSchedule/assets/148116566/b5ca8b26-df87-4f93-89c4-6edef2fdbb1f)

**Comment by Locked15** [comment]
Like this.
![изображение](https://github.com/Locked15/UksivtSchedule_ClientSchedule/assets/79941113/a64f3a78-57f6-4a0c-a9ab-288b5a22dc18)

**Comment by Locked15** [comment]
In one day.
In the future.
